# This is the configuration file for mockery, a tool for generating Go mocks.
all: true
dir: resources/mocks/{{.InterfaceDirRelative}}
log-level: Warn
filename: "mock_{{.InterfaceName}}.go"
template: testify
template-data:
    unroll-variadic: True
force-file-write: True
packages:
    github.com/arielsrv/go-kvs-client/kvs:
        config:
            recursive: true
