# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'

env:
    TF_FOLDER: resources/setup/terraform

tasks:
    tf:clean:
        cmds:
            - rm -rf {{.TF_FOLDER}}/.terraform
            - rm -rf {{.TF_FOLDER}}/.terraform.lock.hcl
            - rm -rf {{.TF_FOLDER}}/terraform.tfstate
    tf:init:
        cmds:
            - (cd {{.TF_FOLDER}} || exit ; tflocal init)
    tf:apply:
        cmds:
            - (cd {{.TF_FOLDER}} || exit ; tflocal apply -auto-approve)
    lint:
        desc: Use golangci-lint (.golangci.yml).
        cmds:
            - go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run --fix
            - go run mvdan.cc/gofumpt@latest -w -l .
            - go run github.com/dkorunic/betteralign/cmd/betteralign@latest -test_files -generated_files -apply ./...
    test:race:
        desc: Race condition test
        cmds:
            - CGO_ENABLED=0 go test -race -count 1 ./... -v
    test:mock:
        desc: Create mocks
        cmds:
            - mockery --config .mockery.yaml
    download:
        desc: Run go mod tidy.
        cmds:
            - go mod tidy
    upgrade:
        desc: Check for latest direct dependencies.
        cmds:
            - go-mod-upgrade
