# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'

env:
    TF_FOLDER: resources/setup/terraform
    CGO_ENABLED: '{{if eq OS "linux"}}1{{else}}0{{end}}'

tasks:
    docker:compose:
        vars:
            CONFIG_FOLDER: resources/setup/docker
        cmds:
            - (cd "{{.CONFIG_FOLDER}}" ||exit ; docker-compose down ; docker-compose up --build)
    awslocal:update:
        silent: true
        cmds:
            - pip install --upgrade pip
            - localstack update all
    awslocal:start:
        silent: true
        env:
            LOCALSTACK_DYNAMODB_REMOVE_EXPIRED_ITEMS: 1
        cmds:
            - localstack start -d
    awslocal:stop:
        silent: true
        cmds:
            - localstack stop
    tf:clean:
        cmds:
            - rm -rf {{.TF_FOLDER}}/.terraform
            - rm -rf {{.TF_FOLDER}}/.terraform.lock.hcl
            - rm -rf {{.TF_FOLDER}}/terraform.tfstate
    tf:lint:
        cmds:
            - (cd {{.TF_FOLDER}} || exit ; tflint)
    tf:init:
        cmds:
            - (cd {{.TF_FOLDER}} || exit ; tflocal init)
    tf:apply:
        cmds:
            - (cd {{.TF_FOLDER}} || exit ; tflocal apply -auto-approve)
    aws:dynamodb:
        vars:
            TABLE_NAME: '__kvs-users-store'
            REGION: eu-west-1
        cmds:
            - 'awslocal dynamodb describe-table --table-name {{.TABLE_NAME}} --region {{.REGION}}'
            - 'awslocal dynamodb describe-time-to-live --table-name {{.TABLE_NAME}} --region {{.REGION}}'
            - 'curl -X DELETE localhost:4566/_aws/dynamodb/expired'
    lint:
        cmds:
            - go tool golangci-lint run --fix
            - go tool gofumpt -w -l .
            - go tool betteralign -test_files -generated_files -apply ./...
    test:race:
        cmds:
            - go test -race -count 5 ./... -v
    test:mock:
        cmds:
            - go tool mockery --config .mockery.yaml
    test:
        cmds:
            -   task: test:mock
            - go test -v ./...
            -   task: test:race
    download:
        cmds:
            - go work sync
            - (cd examples || exit ; go mod tidy)
            - go mod tidy
    upgrade:
        cmds:
            - go tool go-mod-upgrade
    sonar:
        vars:
            SONAR_HOST: https://sonarqube.tooling.dp.iskaypet.com
        cmds:
            - |
                if [ -z "$SONAR_TOKEN" ]; then
                  echo "Error: SONAR_TOKEN is not set."
                  exit 1
                fi
                GOEXPERIMENT=nocoverageredesign go test -coverprofile=coverage.out ./... || true
                go tool golangci-lint run --fix || true
                sonar-scanner -Dsonar.host.url={{.SONAR_HOST}}
    default:
        cmds:
            -   task: download
            -   task: lint
            -   task: test
