# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'

env:
    TF_FOLDER: resources/setup/terraform
    CGO_ENABLED: '{{if eq OS "linux"}}1{{else}}0{{end}}'

tasks:
    tf:clean:
        cmds:
            - rm -rf {{.TF_FOLDER}}/.terraform
            - rm -rf {{.TF_FOLDER}}/.terraform.lock.hcl
            - rm -rf {{.TF_FOLDER}}/terraform.tfstate
    tf:init:
        cmds:
            - (cd {{.TF_FOLDER}} || exit ; tflocal init)
    tf:apply:
        cmds:
            - (cd {{.TF_FOLDER}} || exit ; tflocal apply -auto-approve)
    aws:dynamodb:
        vars:
            TABLE_NAME: '__kvs-users-store'
        cmds:
            - 'awslocal dynamodb describe-table --table-name {{.TABLE_NAME}}'
            - 'awslocal dynamodb describe-time-to-live --table-name {{.TABLE_NAME}}'
    lint:
        cmds:
            - go tool golangci-lint run --fix
            - go tool gofumpt -w -l .
            - go tool betteralign -test_files -generated_files -apply ./...
    test:race:
        cmds:
            - go test -race -count 5 ./... -v
    test:mock:
        cmds:
            - go tool mockery --config .mockery.yaml
    test:
        cmds:
            - task: test:mock
            - go test -v ./...
            - task: test:race
    download:
        cmds:
            - go mod tidy
    upgrade:
        cmds:
            - go tool go-mod-upgrade
    default:
        cmds:
            - task: download
            - task: lint
            - task: test
