// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package redis

import (
	"context"
	"time"

	"github.com/arielsrv/go-kvs-client/kvs/redis"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(err error) *MockClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockClient
func (_mock *MockClient) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockClient_Expecter) Get(ctx interface{}, key interface{}) *MockClient_Get_Call {
	return &MockClient_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockClient_Get_Call) Run(run func(ctx context.Context, key string)) *MockClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Get_Call) Return(s string, err error) *MockClient_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// MGet provides a mock function for the type MockClient
func (_mock *MockClient) MGet(ctx context.Context, keys []string) ([]redis.GetResult, error) {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for MGet")
	}

	var r0 []redis.GetResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]redis.GetResult, error)); ok {
		return returnFunc(ctx, keys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []redis.GetResult); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]redis.GetResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, keys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_MGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MGet'
type MockClient_MGet_Call struct {
	*mock.Call
}

// MGet is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockClient_Expecter) MGet(ctx interface{}, keys interface{}) *MockClient_MGet_Call {
	return &MockClient_MGet_Call{Call: _e.mock.On("MGet", ctx, keys)}
}

func (_c *MockClient_MGet_Call) Run(run func(ctx context.Context, keys []string)) *MockClient_MGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_MGet_Call) Return(getResults []redis.GetResult, err error) *MockClient_MGet_Call {
	_c.Call.Return(getResults, err)
	return _c
}

func (_c *MockClient_MGet_Call) RunAndReturn(run func(ctx context.Context, keys []string) ([]redis.GetResult, error)) *MockClient_MGet_Call {
	_c.Call.Return(run)
	return _c
}

// MSet provides a mock function for the type MockClient
func (_mock *MockClient) MSet(ctx context.Context, pairs []redis.Pair) error {
	ret := _mock.Called(ctx, pairs)

	if len(ret) == 0 {
		panic("no return value specified for MSet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []redis.Pair) error); ok {
		r0 = returnFunc(ctx, pairs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_MSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MSet'
type MockClient_MSet_Call struct {
	*mock.Call
}

// MSet is a helper method to define mock.On call
//   - ctx context.Context
//   - pairs []redis.Pair
func (_e *MockClient_Expecter) MSet(ctx interface{}, pairs interface{}) *MockClient_MSet_Call {
	return &MockClient_MSet_Call{Call: _e.mock.On("MSet", ctx, pairs)}
}

func (_c *MockClient_MSet_Call) Run(run func(ctx context.Context, pairs []redis.Pair)) *MockClient_MSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []redis.Pair
		if args[1] != nil {
			arg1 = args[1].([]redis.Pair)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_MSet_Call) Return(err error) *MockClient_MSet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_MSet_Call) RunAndReturn(run func(ctx context.Context, pairs []redis.Pair) error) *MockClient_MSet_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockClient
func (_mock *MockClient) Set(ctx context.Context, key string, value string, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockClient_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
//   - ttl time.Duration
func (_e *MockClient_Expecter) Set(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *MockClient_Set_Call {
	return &MockClient_Set_Call{Call: _e.mock.On("Set", ctx, key, value, ttl)}
}

func (_c *MockClient_Set_Call) Run(run func(ctx context.Context, key string, value string, ttl time.Duration)) *MockClient_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_Set_Call) Return(err error) *MockClient_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value string, ttl time.Duration) error) *MockClient_Set_Call {
	_c.Call.Return(run)
	return _c
}
