// Code generated by mockery. DO NOT EDIT.

package infrastructure

import mock "github.com/stretchr/testify/mock"

// MockClient is an autogenerated mock type for the Client type
type MockClient[T interface{}] struct {
	mock.Mock
}

type MockClient_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockClient[T]) EXPECT() *MockClient_Expecter[T] {
	return &MockClient_Expecter[T]{mock: &_m.Mock}
}

// BulkGet provides a mock function with given fields: key
func (_m *MockClient[T]) BulkGet(key []string) ([]T, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for BulkGet")
	}

	var r0 []T
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) ([]T, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func([]string) []T); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_BulkGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGet'
type MockClient_BulkGet_Call[T interface{}] struct {
	*mock.Call
}

// BulkGet is a helper method to define mock.On call
//   - key []string
func (_e *MockClient_Expecter[T]) BulkGet(key interface{}) *MockClient_BulkGet_Call[T] {
	return &MockClient_BulkGet_Call[T]{Call: _e.mock.On("BulkGet", key)}
}

func (_c *MockClient_BulkGet_Call[T]) Run(run func(key []string)) *MockClient_BulkGet_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockClient_BulkGet_Call[T]) Return(_a0 []T, _a1 error) *MockClient_BulkGet_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_BulkGet_Call[T]) RunAndReturn(run func([]string) ([]T, error)) *MockClient_BulkGet_Call[T] {
	_c.Call.Return(run)
	return _c
}

// BulkSave provides a mock function with given fields: items, keyMapper
func (_m *MockClient[T]) BulkSave(items []T, keyMapper func(T) string) error {
	ret := _m.Called(items, keyMapper)

	if len(ret) == 0 {
		panic("no return value specified for BulkSave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]T, func(T) string) error); ok {
		r0 = rf(items, keyMapper)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_BulkSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSave'
type MockClient_BulkSave_Call[T interface{}] struct {
	*mock.Call
}

// BulkSave is a helper method to define mock.On call
//   - items []T
//   - keyMapper func(T) string
func (_e *MockClient_Expecter[T]) BulkSave(items interface{}, keyMapper interface{}) *MockClient_BulkSave_Call[T] {
	return &MockClient_BulkSave_Call[T]{Call: _e.mock.On("BulkSave", items, keyMapper)}
}

func (_c *MockClient_BulkSave_Call[T]) Run(run func(items []T, keyMapper func(T) string)) *MockClient_BulkSave_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]T), args[1].(func(T) string))
	})
	return _c
}

func (_c *MockClient_BulkSave_Call[T]) Return(_a0 error) *MockClient_BulkSave_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_BulkSave_Call[T]) RunAndReturn(run func([]T, func(T) string) error) *MockClient_BulkSave_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *MockClient[T]) Get(key string) (*T, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *T
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*T, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *T); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClient_Get_Call[T interface{}] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockClient_Expecter[T]) Get(key interface{}) *MockClient_Get_Call[T] {
	return &MockClient_Get_Call[T]{Call: _e.mock.On("Get", key)}
}

func (_c *MockClient_Get_Call[T]) Run(run func(key string)) *MockClient_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_Get_Call[T]) Return(_a0 *T, _a1 error) *MockClient_Get_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Get_Call[T]) RunAndReturn(run func(string) (*T, error)) *MockClient_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: key, item
func (_m *MockClient[T]) Save(key string, item *T) error {
	ret := _m.Called(key, item)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *T) error); ok {
		r0 = rf(key, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockClient_Save_Call[T interface{}] struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - key string
//   - item *T
func (_e *MockClient_Expecter[T]) Save(key interface{}, item interface{}) *MockClient_Save_Call[T] {
	return &MockClient_Save_Call[T]{Call: _e.mock.On("Save", key, item)}
}

func (_c *MockClient_Save_Call[T]) Run(run func(key string, item *T)) *MockClient_Save_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*T))
	})
	return _c
}

func (_c *MockClient_Save_Call[T]) Return(_a0 error) *MockClient_Save_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Save_Call[T]) RunAndReturn(run func(string, *T) error) *MockClient_Save_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient[T] {
	mock := &MockClient[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
