// Code generated by mockery. DO NOT EDIT.

package infrastructure

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockKVSClient is an autogenerated mock type for the KVSClient type
type MockKVSClient[T interface{}] struct {
	mock.Mock
}

type MockKVSClient_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockKVSClient[T]) EXPECT() *MockKVSClient_Expecter[T] {
	return &MockKVSClient_Expecter[T]{mock: &_m.Mock}
}

// BulkGet provides a mock function with given fields: key
func (_m *MockKVSClient[T]) BulkGet(key []string) ([]T, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for BulkGet")
	}

	var r0 []T
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) ([]T, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func([]string) []T); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKVSClient_BulkGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGet'
type MockKVSClient_BulkGet_Call[T interface{}] struct {
	*mock.Call
}

// BulkGet is a helper method to define mock.On call
//   - key []string
func (_e *MockKVSClient_Expecter[T]) BulkGet(key interface{}) *MockKVSClient_BulkGet_Call[T] {
	return &MockKVSClient_BulkGet_Call[T]{Call: _e.mock.On("BulkGet", key)}
}

func (_c *MockKVSClient_BulkGet_Call[T]) Run(run func(key []string)) *MockKVSClient_BulkGet_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockKVSClient_BulkGet_Call[T]) Return(_a0 []T, _a1 error) *MockKVSClient_BulkGet_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKVSClient_BulkGet_Call[T]) RunAndReturn(run func([]string) ([]T, error)) *MockKVSClient_BulkGet_Call[T] {
	_c.Call.Return(run)
	return _c
}

// BulkGetWithContext provides a mock function with given fields: ctx, keys
func (_m *MockKVSClient[T]) BulkGetWithContext(ctx context.Context, keys []string) ([]T, error) {
	ret := _m.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for BulkGetWithContext")
	}

	var r0 []T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]T, error)); ok {
		return rf(ctx, keys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []T); ok {
		r0 = rf(ctx, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, keys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKVSClient_BulkGetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGetWithContext'
type MockKVSClient_BulkGetWithContext_Call[T interface{}] struct {
	*mock.Call
}

// BulkGetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockKVSClient_Expecter[T]) BulkGetWithContext(ctx interface{}, keys interface{}) *MockKVSClient_BulkGetWithContext_Call[T] {
	return &MockKVSClient_BulkGetWithContext_Call[T]{Call: _e.mock.On("BulkGetWithContext", ctx, keys)}
}

func (_c *MockKVSClient_BulkGetWithContext_Call[T]) Run(run func(ctx context.Context, keys []string)) *MockKVSClient_BulkGetWithContext_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockKVSClient_BulkGetWithContext_Call[T]) Return(_a0 []T, _a1 error) *MockKVSClient_BulkGetWithContext_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKVSClient_BulkGetWithContext_Call[T]) RunAndReturn(run func(context.Context, []string) ([]T, error)) *MockKVSClient_BulkGetWithContext_Call[T] {
	_c.Call.Return(run)
	return _c
}

// BulkSave provides a mock function with given fields: items, keyMapper
func (_m *MockKVSClient[T]) BulkSave(items []T, keyMapper func(T) string) error {
	ret := _m.Called(items, keyMapper)

	if len(ret) == 0 {
		panic("no return value specified for BulkSave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]T, func(T) string) error); ok {
		r0 = rf(items, keyMapper)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKVSClient_BulkSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSave'
type MockKVSClient_BulkSave_Call[T interface{}] struct {
	*mock.Call
}

// BulkSave is a helper method to define mock.On call
//   - items []T
//   - keyMapper func(T) string
func (_e *MockKVSClient_Expecter[T]) BulkSave(items interface{}, keyMapper interface{}) *MockKVSClient_BulkSave_Call[T] {
	return &MockKVSClient_BulkSave_Call[T]{Call: _e.mock.On("BulkSave", items, keyMapper)}
}

func (_c *MockKVSClient_BulkSave_Call[T]) Run(run func(items []T, keyMapper func(T) string)) *MockKVSClient_BulkSave_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]T), args[1].(func(T) string))
	})
	return _c
}

func (_c *MockKVSClient_BulkSave_Call[T]) Return(_a0 error) *MockKVSClient_BulkSave_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKVSClient_BulkSave_Call[T]) RunAndReturn(run func([]T, func(T) string) error) *MockKVSClient_BulkSave_Call[T] {
	_c.Call.Return(run)
	return _c
}

// BulkSaveWithContext provides a mock function with given fields: ctx, items, keyMapper
func (_m *MockKVSClient[T]) BulkSaveWithContext(ctx context.Context, items []T, keyMapper func(T) string) error {
	ret := _m.Called(ctx, items, keyMapper)

	if len(ret) == 0 {
		panic("no return value specified for BulkSaveWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []T, func(T) string) error); ok {
		r0 = rf(ctx, items, keyMapper)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKVSClient_BulkSaveWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSaveWithContext'
type MockKVSClient_BulkSaveWithContext_Call[T interface{}] struct {
	*mock.Call
}

// BulkSaveWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - items []T
//   - keyMapper func(T) string
func (_e *MockKVSClient_Expecter[T]) BulkSaveWithContext(ctx interface{}, items interface{}, keyMapper interface{}) *MockKVSClient_BulkSaveWithContext_Call[T] {
	return &MockKVSClient_BulkSaveWithContext_Call[T]{Call: _e.mock.On("BulkSaveWithContext", ctx, items, keyMapper)}
}

func (_c *MockKVSClient_BulkSaveWithContext_Call[T]) Run(run func(ctx context.Context, items []T, keyMapper func(T) string)) *MockKVSClient_BulkSaveWithContext_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]T), args[2].(func(T) string))
	})
	return _c
}

func (_c *MockKVSClient_BulkSaveWithContext_Call[T]) Return(_a0 error) *MockKVSClient_BulkSaveWithContext_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKVSClient_BulkSaveWithContext_Call[T]) RunAndReturn(run func(context.Context, []T, func(T) string) error) *MockKVSClient_BulkSaveWithContext_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *MockKVSClient[T]) Get(key string) (*T, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *T
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*T, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *T); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKVSClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockKVSClient_Get_Call[T interface{}] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockKVSClient_Expecter[T]) Get(key interface{}) *MockKVSClient_Get_Call[T] {
	return &MockKVSClient_Get_Call[T]{Call: _e.mock.On("Get", key)}
}

func (_c *MockKVSClient_Get_Call[T]) Run(run func(key string)) *MockKVSClient_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockKVSClient_Get_Call[T]) Return(_a0 *T, _a1 error) *MockKVSClient_Get_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKVSClient_Get_Call[T]) RunAndReturn(run func(string) (*T, error)) *MockKVSClient_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetWithContext provides a mock function with given fields: ctx, key
func (_m *MockKVSClient[T]) GetWithContext(ctx context.Context, key string) (*T, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetWithContext")
	}

	var r0 *T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*T, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *T); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKVSClient_GetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithContext'
type MockKVSClient_GetWithContext_Call[T interface{}] struct {
	*mock.Call
}

// GetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockKVSClient_Expecter[T]) GetWithContext(ctx interface{}, key interface{}) *MockKVSClient_GetWithContext_Call[T] {
	return &MockKVSClient_GetWithContext_Call[T]{Call: _e.mock.On("GetWithContext", ctx, key)}
}

func (_c *MockKVSClient_GetWithContext_Call[T]) Run(run func(ctx context.Context, key string)) *MockKVSClient_GetWithContext_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockKVSClient_GetWithContext_Call[T]) Return(_a0 *T, _a1 error) *MockKVSClient_GetWithContext_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKVSClient_GetWithContext_Call[T]) RunAndReturn(run func(context.Context, string) (*T, error)) *MockKVSClient_GetWithContext_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: key, item
func (_m *MockKVSClient[T]) Save(key string, item *T) error {
	ret := _m.Called(key, item)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *T) error); ok {
		r0 = rf(key, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKVSClient_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockKVSClient_Save_Call[T interface{}] struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - key string
//   - item *T
func (_e *MockKVSClient_Expecter[T]) Save(key interface{}, item interface{}) *MockKVSClient_Save_Call[T] {
	return &MockKVSClient_Save_Call[T]{Call: _e.mock.On("Save", key, item)}
}

func (_c *MockKVSClient_Save_Call[T]) Run(run func(key string, item *T)) *MockKVSClient_Save_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*T))
	})
	return _c
}

func (_c *MockKVSClient_Save_Call[T]) Return(_a0 error) *MockKVSClient_Save_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKVSClient_Save_Call[T]) RunAndReturn(run func(string, *T) error) *MockKVSClient_Save_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SaveWithContext provides a mock function with given fields: ctx, key, item
func (_m *MockKVSClient[T]) SaveWithContext(ctx context.Context, key string, item *T) error {
	ret := _m.Called(ctx, key, item)

	if len(ret) == 0 {
		panic("no return value specified for SaveWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *T) error); ok {
		r0 = rf(ctx, key, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKVSClient_SaveWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWithContext'
type MockKVSClient_SaveWithContext_Call[T interface{}] struct {
	*mock.Call
}

// SaveWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - item *T
func (_e *MockKVSClient_Expecter[T]) SaveWithContext(ctx interface{}, key interface{}, item interface{}) *MockKVSClient_SaveWithContext_Call[T] {
	return &MockKVSClient_SaveWithContext_Call[T]{Call: _e.mock.On("SaveWithContext", ctx, key, item)}
}

func (_c *MockKVSClient_SaveWithContext_Call[T]) Run(run func(ctx context.Context, key string, item *T)) *MockKVSClient_SaveWithContext_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*T))
	})
	return _c
}

func (_c *MockKVSClient_SaveWithContext_Call[T]) Return(_a0 error) *MockKVSClient_SaveWithContext_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKVSClient_SaveWithContext_Call[T]) RunAndReturn(run func(context.Context, string, *T) error) *MockKVSClient_SaveWithContext_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockKVSClient creates a new instance of MockKVSClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKVSClient[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKVSClient[T] {
	mock := &MockKVSClient[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
