// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kvs

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/iskaypetcom/digital/sre/tools/dev/go-kvs-client/kvs"
)

// NewMockKVSClient creates a new instance of MockKVSClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKVSClient[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKVSClient[T] {
	mock := &MockKVSClient[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKVSClient is an autogenerated mock type for the KVSClient type
type MockKVSClient[T any] struct {
	mock.Mock
}

type MockKVSClient_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockKVSClient[T]) EXPECT() *MockKVSClient_Expecter[T] {
	return &MockKVSClient_Expecter[T]{mock: &_m.Mock}
}

// BulkGet provides a mock function for the type MockKVSClient
func (_mock *MockKVSClient[T]) BulkGet(key []string) ([]T, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for BulkGet")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) ([]T, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) []T); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKVSClient_BulkGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGet'
type MockKVSClient_BulkGet_Call[T any] struct {
	*mock.Call
}

// BulkGet is a helper method to define mock.On call
//   - key
func (_e *MockKVSClient_Expecter[T]) BulkGet(key interface{}) *MockKVSClient_BulkGet_Call[T] {
	return &MockKVSClient_BulkGet_Call[T]{Call: _e.mock.On("BulkGet", key)}
}

func (_c *MockKVSClient_BulkGet_Call[T]) Run(run func(key []string)) *MockKVSClient_BulkGet_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockKVSClient_BulkGet_Call[T]) Return(vs []T, err error) *MockKVSClient_BulkGet_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockKVSClient_BulkGet_Call[T]) RunAndReturn(run func(key []string) ([]T, error)) *MockKVSClient_BulkGet_Call[T] {
	_c.Call.Return(run)
	return _c
}

// BulkGetWithContext provides a mock function for the type MockKVSClient
func (_mock *MockKVSClient[T]) BulkGetWithContext(ctx context.Context, keys []string) ([]T, error) {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for BulkGetWithContext")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]T, error)); ok {
		return returnFunc(ctx, keys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []T); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, keys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKVSClient_BulkGetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGetWithContext'
type MockKVSClient_BulkGetWithContext_Call[T any] struct {
	*mock.Call
}

// BulkGetWithContext is a helper method to define mock.On call
//   - ctx
//   - keys
func (_e *MockKVSClient_Expecter[T]) BulkGetWithContext(ctx interface{}, keys interface{}) *MockKVSClient_BulkGetWithContext_Call[T] {
	return &MockKVSClient_BulkGetWithContext_Call[T]{Call: _e.mock.On("BulkGetWithContext", ctx, keys)}
}

func (_c *MockKVSClient_BulkGetWithContext_Call[T]) Run(run func(ctx context.Context, keys []string)) *MockKVSClient_BulkGetWithContext_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockKVSClient_BulkGetWithContext_Call[T]) Return(vs []T, err error) *MockKVSClient_BulkGetWithContext_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockKVSClient_BulkGetWithContext_Call[T]) RunAndReturn(run func(ctx context.Context, keys []string) ([]T, error)) *MockKVSClient_BulkGetWithContext_Call[T] {
	_c.Call.Return(run)
	return _c
}

// BulkSave provides a mock function for the type MockKVSClient
func (_mock *MockKVSClient[T]) BulkSave(items []T, keyMapper kvs.KeyMapperFunc[T], ttl ...int64) error {
	// int64
	_va := make([]interface{}, len(ttl))
	for _i := range ttl {
		_va[_i] = ttl[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, items, keyMapper)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for BulkSave")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]T, kvs.KeyMapperFunc[T], ...int64) error); ok {
		r0 = returnFunc(items, keyMapper, ttl...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKVSClient_BulkSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSave'
type MockKVSClient_BulkSave_Call[T any] struct {
	*mock.Call
}

// BulkSave is a helper method to define mock.On call
//   - items
//   - keyMapper
//   - ttl
func (_e *MockKVSClient_Expecter[T]) BulkSave(items interface{}, keyMapper interface{}, ttl ...interface{}) *MockKVSClient_BulkSave_Call[T] {
	return &MockKVSClient_BulkSave_Call[T]{Call: _e.mock.On("BulkSave",
		append([]interface{}{items, keyMapper}, ttl...)...)}
}

func (_c *MockKVSClient_BulkSave_Call[T]) Run(run func(items []T, keyMapper kvs.KeyMapperFunc[T], ttl ...int64)) *MockKVSClient_BulkSave_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]int64, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(int64)
			}
		}
		run(args[0].([]T), args[1].(kvs.KeyMapperFunc[T]), variadicArgs...)
	})
	return _c
}

func (_c *MockKVSClient_BulkSave_Call[T]) Return(err error) *MockKVSClient_BulkSave_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKVSClient_BulkSave_Call[T]) RunAndReturn(run func(items []T, keyMapper kvs.KeyMapperFunc[T], ttl ...int64) error) *MockKVSClient_BulkSave_Call[T] {
	_c.Call.Return(run)
	return _c
}

// BulkSaveWithContext provides a mock function for the type MockKVSClient
func (_mock *MockKVSClient[T]) BulkSaveWithContext(ctx context.Context, items []T, keyMapper kvs.KeyMapperFunc[T], ttl ...int64) error {
	// int64
	_va := make([]interface{}, len(ttl))
	for _i := range ttl {
		_va[_i] = ttl[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, items, keyMapper)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for BulkSaveWithContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []T, kvs.KeyMapperFunc[T], ...int64) error); ok {
		r0 = returnFunc(ctx, items, keyMapper, ttl...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKVSClient_BulkSaveWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSaveWithContext'
type MockKVSClient_BulkSaveWithContext_Call[T any] struct {
	*mock.Call
}

// BulkSaveWithContext is a helper method to define mock.On call
//   - ctx
//   - items
//   - keyMapper
//   - ttl
func (_e *MockKVSClient_Expecter[T]) BulkSaveWithContext(ctx interface{}, items interface{}, keyMapper interface{}, ttl ...interface{}) *MockKVSClient_BulkSaveWithContext_Call[T] {
	return &MockKVSClient_BulkSaveWithContext_Call[T]{Call: _e.mock.On("BulkSaveWithContext",
		append([]interface{}{ctx, items, keyMapper}, ttl...)...)}
}

func (_c *MockKVSClient_BulkSaveWithContext_Call[T]) Run(run func(ctx context.Context, items []T, keyMapper kvs.KeyMapperFunc[T], ttl ...int64)) *MockKVSClient_BulkSaveWithContext_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]int64, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(int64)
			}
		}
		run(args[0].(context.Context), args[1].([]T), args[2].(kvs.KeyMapperFunc[T]), variadicArgs...)
	})
	return _c
}

func (_c *MockKVSClient_BulkSaveWithContext_Call[T]) Return(err error) *MockKVSClient_BulkSaveWithContext_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKVSClient_BulkSaveWithContext_Call[T]) RunAndReturn(run func(ctx context.Context, items []T, keyMapper kvs.KeyMapperFunc[T], ttl ...int64) error) *MockKVSClient_BulkSaveWithContext_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockKVSClient
func (_mock *MockKVSClient[T]) Get(key string) (*T, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*T, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *T); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKVSClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockKVSClient_Get_Call[T any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key
func (_e *MockKVSClient_Expecter[T]) Get(key interface{}) *MockKVSClient_Get_Call[T] {
	return &MockKVSClient_Get_Call[T]{Call: _e.mock.On("Get", key)}
}

func (_c *MockKVSClient_Get_Call[T]) Run(run func(key string)) *MockKVSClient_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockKVSClient_Get_Call[T]) Return(v *T, err error) *MockKVSClient_Get_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockKVSClient_Get_Call[T]) RunAndReturn(run func(key string) (*T, error)) *MockKVSClient_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetWithContext provides a mock function for the type MockKVSClient
func (_mock *MockKVSClient[T]) GetWithContext(ctx context.Context, key string) (*T, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetWithContext")
	}

	var r0 *T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*T, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *T); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKVSClient_GetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithContext'
type MockKVSClient_GetWithContext_Call[T any] struct {
	*mock.Call
}

// GetWithContext is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *MockKVSClient_Expecter[T]) GetWithContext(ctx interface{}, key interface{}) *MockKVSClient_GetWithContext_Call[T] {
	return &MockKVSClient_GetWithContext_Call[T]{Call: _e.mock.On("GetWithContext", ctx, key)}
}

func (_c *MockKVSClient_GetWithContext_Call[T]) Run(run func(ctx context.Context, key string)) *MockKVSClient_GetWithContext_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockKVSClient_GetWithContext_Call[T]) Return(v *T, err error) *MockKVSClient_GetWithContext_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockKVSClient_GetWithContext_Call[T]) RunAndReturn(run func(ctx context.Context, key string) (*T, error)) *MockKVSClient_GetWithContext_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockKVSClient
func (_mock *MockKVSClient[T]) Save(key string, item *T, ttl ...int64) error {
	// int64
	_va := make([]interface{}, len(ttl))
	for _i := range ttl {
		_va[_i] = ttl[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, key, item)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *T, ...int64) error); ok {
		r0 = returnFunc(key, item, ttl...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKVSClient_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockKVSClient_Save_Call[T any] struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - key
//   - item
//   - ttl
func (_e *MockKVSClient_Expecter[T]) Save(key interface{}, item interface{}, ttl ...interface{}) *MockKVSClient_Save_Call[T] {
	return &MockKVSClient_Save_Call[T]{Call: _e.mock.On("Save",
		append([]interface{}{key, item}, ttl...)...)}
}

func (_c *MockKVSClient_Save_Call[T]) Run(run func(key string, item *T, ttl ...int64)) *MockKVSClient_Save_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]int64, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(int64)
			}
		}
		run(args[0].(string), args[1].(*T), variadicArgs...)
	})
	return _c
}

func (_c *MockKVSClient_Save_Call[T]) Return(err error) *MockKVSClient_Save_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKVSClient_Save_Call[T]) RunAndReturn(run func(key string, item *T, ttl ...int64) error) *MockKVSClient_Save_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SaveWithContext provides a mock function for the type MockKVSClient
func (_mock *MockKVSClient[T]) SaveWithContext(ctx context.Context, key string, item *T, ttl ...int64) error {
	// int64
	_va := make([]interface{}, len(ttl))
	for _i := range ttl {
		_va[_i] = ttl[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key, item)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SaveWithContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *T, ...int64) error); ok {
		r0 = returnFunc(ctx, key, item, ttl...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKVSClient_SaveWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWithContext'
type MockKVSClient_SaveWithContext_Call[T any] struct {
	*mock.Call
}

// SaveWithContext is a helper method to define mock.On call
//   - ctx
//   - key
//   - item
//   - ttl
func (_e *MockKVSClient_Expecter[T]) SaveWithContext(ctx interface{}, key interface{}, item interface{}, ttl ...interface{}) *MockKVSClient_SaveWithContext_Call[T] {
	return &MockKVSClient_SaveWithContext_Call[T]{Call: _e.mock.On("SaveWithContext",
		append([]interface{}{ctx, key, item}, ttl...)...)}
}

func (_c *MockKVSClient_SaveWithContext_Call[T]) Run(run func(ctx context.Context, key string, item *T, ttl ...int64)) *MockKVSClient_SaveWithContext_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]int64, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(int64)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(*T), variadicArgs...)
	})
	return _c
}

func (_c *MockKVSClient_SaveWithContext_Call[T]) Return(err error) *MockKVSClient_SaveWithContext_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKVSClient_SaveWithContext_Call[T]) RunAndReturn(run func(ctx context.Context, key string, item *T, ttl ...int64) error) *MockKVSClient_SaveWithContext_Call[T] {
	_c.Call.Return(run)
	return _c
}
