// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kvs

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/iskaypetcom/digital/sre/tools/dev/go-kvs-client/kvs"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient[T] {
	mock := &MockClient[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient[T any] struct {
	mock.Mock
}

type MockClient_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockClient[T]) EXPECT() *MockClient_Expecter[T] {
	return &MockClient_Expecter[T]{mock: &_m.Mock}
}

// BulkGet provides a mock function for the type MockClient
func (_mock *MockClient[T]) BulkGet(key []string) ([]T, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for BulkGet")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) ([]T, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) []T); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_BulkGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGet'
type MockClient_BulkGet_Call[T any] struct {
	*mock.Call
}

// BulkGet is a helper method to define mock.On call
//   - key []string
func (_e *MockClient_Expecter[T]) BulkGet(key interface{}) *MockClient_BulkGet_Call[T] {
	return &MockClient_BulkGet_Call[T]{Call: _e.mock.On("BulkGet", key)}
}

func (_c *MockClient_BulkGet_Call[T]) Run(run func(key []string)) *MockClient_BulkGet_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_BulkGet_Call[T]) Return(vs []T, err error) *MockClient_BulkGet_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockClient_BulkGet_Call[T]) RunAndReturn(run func(key []string) ([]T, error)) *MockClient_BulkGet_Call[T] {
	_c.Call.Return(run)
	return _c
}

// BulkGetWithContext provides a mock function for the type MockClient
func (_mock *MockClient[T]) BulkGetWithContext(ctx context.Context, keys []string) ([]T, error) {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for BulkGetWithContext")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]T, error)); ok {
		return returnFunc(ctx, keys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []T); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, keys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_BulkGetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGetWithContext'
type MockClient_BulkGetWithContext_Call[T any] struct {
	*mock.Call
}

// BulkGetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockClient_Expecter[T]) BulkGetWithContext(ctx interface{}, keys interface{}) *MockClient_BulkGetWithContext_Call[T] {
	return &MockClient_BulkGetWithContext_Call[T]{Call: _e.mock.On("BulkGetWithContext", ctx, keys)}
}

func (_c *MockClient_BulkGetWithContext_Call[T]) Run(run func(ctx context.Context, keys []string)) *MockClient_BulkGetWithContext_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_BulkGetWithContext_Call[T]) Return(vs []T, err error) *MockClient_BulkGetWithContext_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockClient_BulkGetWithContext_Call[T]) RunAndReturn(run func(ctx context.Context, keys []string) ([]T, error)) *MockClient_BulkGetWithContext_Call[T] {
	_c.Call.Return(run)
	return _c
}

// BulkSave provides a mock function for the type MockClient
func (_mock *MockClient[T]) BulkSave(items []T, keyMapper kvs.KeyMapperFunc[T], ttl ...time.Duration) error {
	// time.Duration
	_va := make([]interface{}, len(ttl))
	for _i := range ttl {
		_va[_i] = ttl[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, items, keyMapper)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for BulkSave")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]T, kvs.KeyMapperFunc[T], ...time.Duration) error); ok {
		r0 = returnFunc(items, keyMapper, ttl...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_BulkSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSave'
type MockClient_BulkSave_Call[T any] struct {
	*mock.Call
}

// BulkSave is a helper method to define mock.On call
//   - items []T
//   - keyMapper kvs.KeyMapperFunc[T]
//   - ttl ...time.Duration
func (_e *MockClient_Expecter[T]) BulkSave(items interface{}, keyMapper interface{}, ttl ...interface{}) *MockClient_BulkSave_Call[T] {
	return &MockClient_BulkSave_Call[T]{Call: _e.mock.On("BulkSave",
		append([]interface{}{items, keyMapper}, ttl...)...)}
}

func (_c *MockClient_BulkSave_Call[T]) Run(run func(items []T, keyMapper kvs.KeyMapperFunc[T], ttl ...time.Duration)) *MockClient_BulkSave_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []T
		if args[0] != nil {
			arg0 = args[0].([]T)
		}
		var arg1 kvs.KeyMapperFunc[T]
		if args[1] != nil {
			arg1 = args[1].(kvs.KeyMapperFunc[T])
		}
		var arg2 []time.Duration
		variadicArgs := make([]time.Duration, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(time.Duration)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_BulkSave_Call[T]) Return(err error) *MockClient_BulkSave_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_BulkSave_Call[T]) RunAndReturn(run func(items []T, keyMapper kvs.KeyMapperFunc[T], ttl ...time.Duration) error) *MockClient_BulkSave_Call[T] {
	_c.Call.Return(run)
	return _c
}

// BulkSaveWithContext provides a mock function for the type MockClient
func (_mock *MockClient[T]) BulkSaveWithContext(ctx context.Context, items []T, keyMapper kvs.KeyMapperFunc[T], ttl ...time.Duration) error {
	// time.Duration
	_va := make([]interface{}, len(ttl))
	for _i := range ttl {
		_va[_i] = ttl[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, items, keyMapper)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for BulkSaveWithContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []T, kvs.KeyMapperFunc[T], ...time.Duration) error); ok {
		r0 = returnFunc(ctx, items, keyMapper, ttl...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_BulkSaveWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSaveWithContext'
type MockClient_BulkSaveWithContext_Call[T any] struct {
	*mock.Call
}

// BulkSaveWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - items []T
//   - keyMapper kvs.KeyMapperFunc[T]
//   - ttl ...time.Duration
func (_e *MockClient_Expecter[T]) BulkSaveWithContext(ctx interface{}, items interface{}, keyMapper interface{}, ttl ...interface{}) *MockClient_BulkSaveWithContext_Call[T] {
	return &MockClient_BulkSaveWithContext_Call[T]{Call: _e.mock.On("BulkSaveWithContext",
		append([]interface{}{ctx, items, keyMapper}, ttl...)...)}
}

func (_c *MockClient_BulkSaveWithContext_Call[T]) Run(run func(ctx context.Context, items []T, keyMapper kvs.KeyMapperFunc[T], ttl ...time.Duration)) *MockClient_BulkSaveWithContext_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []T
		if args[1] != nil {
			arg1 = args[1].([]T)
		}
		var arg2 kvs.KeyMapperFunc[T]
		if args[2] != nil {
			arg2 = args[2].(kvs.KeyMapperFunc[T])
		}
		var arg3 []time.Duration
		variadicArgs := make([]time.Duration, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(time.Duration)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockClient_BulkSaveWithContext_Call[T]) Return(err error) *MockClient_BulkSaveWithContext_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_BulkSaveWithContext_Call[T]) RunAndReturn(run func(ctx context.Context, items []T, keyMapper kvs.KeyMapperFunc[T], ttl ...time.Duration) error) *MockClient_BulkSaveWithContext_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockClient
func (_mock *MockClient[T]) Get(key string) (*T, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*T, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *T); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClient_Get_Call[T any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockClient_Expecter[T]) Get(key interface{}) *MockClient_Get_Call[T] {
	return &MockClient_Get_Call[T]{Call: _e.mock.On("Get", key)}
}

func (_c *MockClient_Get_Call[T]) Run(run func(key string)) *MockClient_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Get_Call[T]) Return(v *T, err error) *MockClient_Get_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_Get_Call[T]) RunAndReturn(run func(key string) (*T, error)) *MockClient_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetWithContext provides a mock function for the type MockClient
func (_mock *MockClient[T]) GetWithContext(ctx context.Context, key string) (*T, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetWithContext")
	}

	var r0 *T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*T, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *T); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithContext'
type MockClient_GetWithContext_Call[T any] struct {
	*mock.Call
}

// GetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockClient_Expecter[T]) GetWithContext(ctx interface{}, key interface{}) *MockClient_GetWithContext_Call[T] {
	return &MockClient_GetWithContext_Call[T]{Call: _e.mock.On("GetWithContext", ctx, key)}
}

func (_c *MockClient_GetWithContext_Call[T]) Run(run func(ctx context.Context, key string)) *MockClient_GetWithContext_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetWithContext_Call[T]) Return(v *T, err error) *MockClient_GetWithContext_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_GetWithContext_Call[T]) RunAndReturn(run func(ctx context.Context, key string) (*T, error)) *MockClient_GetWithContext_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockClient
func (_mock *MockClient[T]) Save(key string, item *T, ttl ...time.Duration) error {
	// time.Duration
	_va := make([]interface{}, len(ttl))
	for _i := range ttl {
		_va[_i] = ttl[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, key, item)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *T, ...time.Duration) error); ok {
		r0 = returnFunc(key, item, ttl...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockClient_Save_Call[T any] struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - key string
//   - item *T
//   - ttl ...time.Duration
func (_e *MockClient_Expecter[T]) Save(key interface{}, item interface{}, ttl ...interface{}) *MockClient_Save_Call[T] {
	return &MockClient_Save_Call[T]{Call: _e.mock.On("Save",
		append([]interface{}{key, item}, ttl...)...)}
}

func (_c *MockClient_Save_Call[T]) Run(run func(key string, item *T, ttl ...time.Duration)) *MockClient_Save_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *T
		if args[1] != nil {
			arg1 = args[1].(*T)
		}
		var arg2 []time.Duration
		variadicArgs := make([]time.Duration, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(time.Duration)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_Save_Call[T]) Return(err error) *MockClient_Save_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Save_Call[T]) RunAndReturn(run func(key string, item *T, ttl ...time.Duration) error) *MockClient_Save_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SaveWithContext provides a mock function for the type MockClient
func (_mock *MockClient[T]) SaveWithContext(ctx context.Context, key string, item *T, ttl ...time.Duration) error {
	// time.Duration
	_va := make([]interface{}, len(ttl))
	for _i := range ttl {
		_va[_i] = ttl[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key, item)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SaveWithContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *T, ...time.Duration) error); ok {
		r0 = returnFunc(ctx, key, item, ttl...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_SaveWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWithContext'
type MockClient_SaveWithContext_Call[T any] struct {
	*mock.Call
}

// SaveWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - item *T
//   - ttl ...time.Duration
func (_e *MockClient_Expecter[T]) SaveWithContext(ctx interface{}, key interface{}, item interface{}, ttl ...interface{}) *MockClient_SaveWithContext_Call[T] {
	return &MockClient_SaveWithContext_Call[T]{Call: _e.mock.On("SaveWithContext",
		append([]interface{}{ctx, key, item}, ttl...)...)}
}

func (_c *MockClient_SaveWithContext_Call[T]) Run(run func(ctx context.Context, key string, item *T, ttl ...time.Duration)) *MockClient_SaveWithContext_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *T
		if args[2] != nil {
			arg2 = args[2].(*T)
		}
		var arg3 []time.Duration
		variadicArgs := make([]time.Duration, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(time.Duration)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockClient_SaveWithContext_Call[T]) Return(err error) *MockClient_SaveWithContext_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_SaveWithContext_Call[T]) RunAndReturn(run func(ctx context.Context, key string, item *T, ttl ...time.Duration) error) *MockClient_SaveWithContext_Call[T] {
	_c.Call.Return(run)
	return _c
}
