// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kvs

import (
	"iter"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/iskaypetcom/digital/sre/tools/dev/go-kvs-client/kvs"
)

// NewMockIterable creates a new instance of MockIterable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIterable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIterable {
	mock := &MockIterable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIterable is an autogenerated mock type for the Iterable type
type MockIterable struct {
	mock.Mock
}

type MockIterable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIterable) EXPECT() *MockIterable_Expecter {
	return &MockIterable_Expecter{mock: &_m.Mock}
}

// All provides a mock function for the type MockIterable
func (_mock *MockIterable) All() iter.Seq[*kvs.Item] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 iter.Seq[*kvs.Item]
	if returnFunc, ok := ret.Get(0).(func() iter.Seq[*kvs.Item]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq[*kvs.Item])
		}
	}
	return r0
}

// MockIterable_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockIterable_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
func (_e *MockIterable_Expecter) All() *MockIterable_All_Call {
	return &MockIterable_All_Call{Call: _e.mock.On("All")}
}

func (_c *MockIterable_All_Call) Run(run func()) *MockIterable_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIterable_All_Call) Return(seq iter.Seq[*kvs.Item]) *MockIterable_All_Call {
	_c.Call.Return(seq)
	return _c
}

func (_c *MockIterable_All_Call) RunAndReturn(run func() iter.Seq[*kvs.Item]) *MockIterable_All_Call {
	_c.Call.Return(run)
	return _c
}
