// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kvs

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/iskaypetcom/digital/sre/tools/dev/go-kvs-client/kvs"
)

// NewMockIClient creates a new instance of MockIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIClient {
	mock := &MockIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIClient is an autogenerated mock type for the LowLevelClient type
type MockIClient struct {
	mock.Mock
}

type MockIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIClient) EXPECT() *MockIClient_Expecter {
	return &MockIClient_Expecter{mock: &_m.Mock}
}

// BulkGet provides a mock function for the type MockIClient
func (_mock *MockIClient) BulkGet(keys []string) (*kvs.Items, error) {
	ret := _mock.Called(keys)

	if len(ret) == 0 {
		panic("no return value specified for BulkGet")
	}

	var r0 *kvs.Items
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) (*kvs.Items, error)); ok {
		return returnFunc(keys)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) *kvs.Items); ok {
		r0 = returnFunc(keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Items)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(keys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIClient_BulkGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGet'
type MockIClient_BulkGet_Call struct {
	*mock.Call
}

// BulkGet is a helper method to define mock.On call
//   - keys
func (_e *MockIClient_Expecter) BulkGet(keys interface{}) *MockIClient_BulkGet_Call {
	return &MockIClient_BulkGet_Call{Call: _e.mock.On("BulkGet", keys)}
}

func (_c *MockIClient_BulkGet_Call) Run(run func(keys []string)) *MockIClient_BulkGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockIClient_BulkGet_Call) Return(items *kvs.Items, err error) *MockIClient_BulkGet_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockIClient_BulkGet_Call) RunAndReturn(run func(keys []string) (*kvs.Items, error)) *MockIClient_BulkGet_Call {
	_c.Call.Return(run)
	return _c
}

// BulkGetWithContext provides a mock function for the type MockIClient
func (_mock *MockIClient) BulkGetWithContext(ctx context.Context, key []string) (*kvs.Items, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for BulkGetWithContext")
	}

	var r0 *kvs.Items
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (*kvs.Items, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) *kvs.Items); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Items)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIClient_BulkGetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGetWithContext'
type MockIClient_BulkGetWithContext_Call struct {
	*mock.Call
}

// BulkGetWithContext is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *MockIClient_Expecter) BulkGetWithContext(ctx interface{}, key interface{}) *MockIClient_BulkGetWithContext_Call {
	return &MockIClient_BulkGetWithContext_Call{Call: _e.mock.On("BulkGetWithContext", ctx, key)}
}

func (_c *MockIClient_BulkGetWithContext_Call) Run(run func(ctx context.Context, key []string)) *MockIClient_BulkGetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockIClient_BulkGetWithContext_Call) Return(items *kvs.Items, err error) *MockIClient_BulkGetWithContext_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockIClient_BulkGetWithContext_Call) RunAndReturn(run func(ctx context.Context, key []string) (*kvs.Items, error)) *MockIClient_BulkGetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// BulkSave provides a mock function for the type MockIClient
func (_mock *MockIClient) BulkSave(items *kvs.Items) error {
	ret := _mock.Called(items)

	if len(ret) == 0 {
		panic("no return value specified for BulkSave")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*kvs.Items) error); ok {
		r0 = returnFunc(items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIClient_BulkSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSave'
type MockIClient_BulkSave_Call struct {
	*mock.Call
}

// BulkSave is a helper method to define mock.On call
//   - items
func (_e *MockIClient_Expecter) BulkSave(items interface{}) *MockIClient_BulkSave_Call {
	return &MockIClient_BulkSave_Call{Call: _e.mock.On("BulkSave", items)}
}

func (_c *MockIClient_BulkSave_Call) Run(run func(items *kvs.Items)) *MockIClient_BulkSave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*kvs.Items))
	})
	return _c
}

func (_c *MockIClient_BulkSave_Call) Return(err error) *MockIClient_BulkSave_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIClient_BulkSave_Call) RunAndReturn(run func(items *kvs.Items) error) *MockIClient_BulkSave_Call {
	_c.Call.Return(run)
	return _c
}

// BulkSaveWithContext provides a mock function for the type MockIClient
func (_mock *MockIClient) BulkSaveWithContext(ctx context.Context, items *kvs.Items) error {
	ret := _mock.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for BulkSaveWithContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kvs.Items) error); ok {
		r0 = returnFunc(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIClient_BulkSaveWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSaveWithContext'
type MockIClient_BulkSaveWithContext_Call struct {
	*mock.Call
}

// BulkSaveWithContext is a helper method to define mock.On call
//   - ctx
//   - items
func (_e *MockIClient_Expecter) BulkSaveWithContext(ctx interface{}, items interface{}) *MockIClient_BulkSaveWithContext_Call {
	return &MockIClient_BulkSaveWithContext_Call{Call: _e.mock.On("BulkSaveWithContext", ctx, items)}
}

func (_c *MockIClient_BulkSaveWithContext_Call) Run(run func(ctx context.Context, items *kvs.Items)) *MockIClient_BulkSaveWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*kvs.Items))
	})
	return _c
}

func (_c *MockIClient_BulkSaveWithContext_Call) Return(err error) *MockIClient_BulkSaveWithContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIClient_BulkSaveWithContext_Call) RunAndReturn(run func(ctx context.Context, items *kvs.Items) error) *MockIClient_BulkSaveWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerName provides a mock function for the type MockIClient
func (_mock *MockIClient) ContainerName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContainerName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIClient_ContainerName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerName'
type MockIClient_ContainerName_Call struct {
	*mock.Call
}

// ContainerName is a helper method to define mock.On call
func (_e *MockIClient_Expecter) ContainerName() *MockIClient_ContainerName_Call {
	return &MockIClient_ContainerName_Call{Call: _e.mock.On("ContainerName")}
}

func (_c *MockIClient_ContainerName_Call) Run(run func()) *MockIClient_ContainerName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIClient_ContainerName_Call) Return(s string) *MockIClient_ContainerName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIClient_ContainerName_Call) RunAndReturn(run func() string) *MockIClient_ContainerName_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockIClient
func (_mock *MockIClient) Get(key string) (*kvs.Item, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *kvs.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*kvs.Item, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *kvs.Item); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key
func (_e *MockIClient_Expecter) Get(key interface{}) *MockIClient_Get_Call {
	return &MockIClient_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockIClient_Get_Call) Run(run func(key string)) *MockIClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIClient_Get_Call) Return(item *kvs.Item, err error) *MockIClient_Get_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockIClient_Get_Call) RunAndReturn(run func(key string) (*kvs.Item, error)) *MockIClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithContext provides a mock function for the type MockIClient
func (_mock *MockIClient) GetWithContext(ctx context.Context, key string) (*kvs.Item, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetWithContext")
	}

	var r0 *kvs.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*kvs.Item, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *kvs.Item); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIClient_GetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithContext'
type MockIClient_GetWithContext_Call struct {
	*mock.Call
}

// GetWithContext is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *MockIClient_Expecter) GetWithContext(ctx interface{}, key interface{}) *MockIClient_GetWithContext_Call {
	return &MockIClient_GetWithContext_Call{Call: _e.mock.On("GetWithContext", ctx, key)}
}

func (_c *MockIClient_GetWithContext_Call) Run(run func(ctx context.Context, key string)) *MockIClient_GetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIClient_GetWithContext_Call) Return(item *kvs.Item, err error) *MockIClient_GetWithContext_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockIClient_GetWithContext_Call) RunAndReturn(run func(ctx context.Context, key string) (*kvs.Item, error)) *MockIClient_GetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockIClient
func (_mock *MockIClient) Save(key string, item *kvs.Item) error {
	ret := _mock.Called(key, item)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *kvs.Item) error); ok {
		r0 = returnFunc(key, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIClient_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockIClient_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - key
//   - item
func (_e *MockIClient_Expecter) Save(key interface{}, item interface{}) *MockIClient_Save_Call {
	return &MockIClient_Save_Call{Call: _e.mock.On("Save", key, item)}
}

func (_c *MockIClient_Save_Call) Run(run func(key string, item *kvs.Item)) *MockIClient_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*kvs.Item))
	})
	return _c
}

func (_c *MockIClient_Save_Call) Return(err error) *MockIClient_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIClient_Save_Call) RunAndReturn(run func(key string, item *kvs.Item) error) *MockIClient_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveWithContext provides a mock function for the type MockIClient
func (_mock *MockIClient) SaveWithContext(ctx context.Context, key string, item *kvs.Item) error {
	ret := _mock.Called(ctx, key, item)

	if len(ret) == 0 {
		panic("no return value specified for SaveWithContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *kvs.Item) error); ok {
		r0 = returnFunc(ctx, key, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIClient_SaveWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWithContext'
type MockIClient_SaveWithContext_Call struct {
	*mock.Call
}

// SaveWithContext is a helper method to define mock.On call
//   - ctx
//   - key
//   - item
func (_e *MockIClient_Expecter) SaveWithContext(ctx interface{}, key interface{}, item interface{}) *MockIClient_SaveWithContext_Call {
	return &MockIClient_SaveWithContext_Call{Call: _e.mock.On("SaveWithContext", ctx, key, item)}
}

func (_c *MockIClient_SaveWithContext_Call) Run(run func(ctx context.Context, key string, item *kvs.Item)) *MockIClient_SaveWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*kvs.Item))
	})
	return _c
}

func (_c *MockIClient_SaveWithContext_Call) Return(err error) *MockIClient_SaveWithContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIClient_SaveWithContext_Call) RunAndReturn(run func(ctx context.Context, key string, item *kvs.Item) error) *MockIClient_SaveWithContext_Call {
	_c.Call.Return(run)
	return _c
}
