// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kvs

import (
	"iter"

	"github.com/arielsrv/go-kvs-client/kvs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockList creates a new instance of MockList. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockList(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockList {
	mock := &MockList{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockList is an autogenerated mock type for the List type
type MockList struct {
	mock.Mock
}

type MockList_Expecter struct {
	mock *mock.Mock
}

func (_m *MockList) EXPECT() *MockList_Expecter {
	return &MockList_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockList
func (_mock *MockList) Add(item *kvs.Item) {
	_mock.Called(item)
	return
}

// MockList_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockList_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - item *kvs.Item
func (_e *MockList_Expecter) Add(item interface{}) *MockList_Add_Call {
	return &MockList_Add_Call{Call: _e.mock.On("Add", item)}
}

func (_c *MockList_Add_Call) Run(run func(item *kvs.Item)) *MockList_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *kvs.Item
		if args[0] != nil {
			arg0 = args[0].(*kvs.Item)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockList_Add_Call) Return() *MockList_Add_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockList_Add_Call) RunAndReturn(run func(item *kvs.Item)) *MockList_Add_Call {
	_c.Run(run)
	return _c
}

// All provides a mock function for the type MockList
func (_mock *MockList) All() iter.Seq[*kvs.Item] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 iter.Seq[*kvs.Item]
	if returnFunc, ok := ret.Get(0).(func() iter.Seq[*kvs.Item]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq[*kvs.Item])
		}
	}
	return r0
}

// MockList_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockList_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
func (_e *MockList_Expecter) All() *MockList_All_Call {
	return &MockList_All_Call{Call: _e.mock.On("All")}
}

func (_c *MockList_All_Call) Run(run func()) *MockList_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockList_All_Call) Return(seq iter.Seq[*kvs.Item]) *MockList_All_Call {
	_c.Call.Return(seq)
	return _c
}

func (_c *MockList_All_Call) RunAndReturn(run func() iter.Seq[*kvs.Item]) *MockList_All_Call {
	_c.Call.Return(run)
	return _c
}

// Len provides a mock function for the type MockList
func (_mock *MockList) Len() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Len")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockList_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type MockList_Len_Call struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
func (_e *MockList_Expecter) Len() *MockList_Len_Call {
	return &MockList_Len_Call{Call: _e.mock.On("Len")}
}

func (_c *MockList_Len_Call) Run(run func()) *MockList_Len_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockList_Len_Call) Return(n int) *MockList_Len_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockList_Len_Call) RunAndReturn(run func() int) *MockList_Len_Call {
	_c.Call.Return(run)
	return _c
}
