// Code generated by mockery. DO NOT EDIT.

package kvs

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	kvs "gitlab.com/iskaypetcom/digital/sre/tools/dev/go-kvs-client/kvs"
)

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// BulkGet provides a mock function with given fields: keys
func (_m *MockReader) BulkGet(keys []string) (*kvs.Items, error) {
	ret := _m.Called(keys)

	if len(ret) == 0 {
		panic("no return value specified for BulkGet")
	}

	var r0 *kvs.Items
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) (*kvs.Items, error)); ok {
		return rf(keys)
	}
	if rf, ok := ret.Get(0).(func([]string) *kvs.Items); ok {
		r0 = rf(keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Items)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(keys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_BulkGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGet'
type MockReader_BulkGet_Call struct {
	*mock.Call
}

// BulkGet is a helper method to define mock.On call
//   - keys []string
func (_e *MockReader_Expecter) BulkGet(keys interface{}) *MockReader_BulkGet_Call {
	return &MockReader_BulkGet_Call{Call: _e.mock.On("BulkGet", keys)}
}

func (_c *MockReader_BulkGet_Call) Run(run func(keys []string)) *MockReader_BulkGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockReader_BulkGet_Call) Return(_a0 *kvs.Items, _a1 error) *MockReader_BulkGet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_BulkGet_Call) RunAndReturn(run func([]string) (*kvs.Items, error)) *MockReader_BulkGet_Call {
	_c.Call.Return(run)
	return _c
}

// BulkGetWithContext provides a mock function with given fields: ctx, key
func (_m *MockReader) BulkGetWithContext(ctx context.Context, key string) (*kvs.Items, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for BulkGetWithContext")
	}

	var r0 *kvs.Items
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*kvs.Items, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *kvs.Items); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Items)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_BulkGetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGetWithContext'
type MockReader_BulkGetWithContext_Call struct {
	*mock.Call
}

// BulkGetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockReader_Expecter) BulkGetWithContext(ctx interface{}, key interface{}) *MockReader_BulkGetWithContext_Call {
	return &MockReader_BulkGetWithContext_Call{Call: _e.mock.On("BulkGetWithContext", ctx, key)}
}

func (_c *MockReader_BulkGetWithContext_Call) Run(run func(ctx context.Context, key string)) *MockReader_BulkGetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReader_BulkGetWithContext_Call) Return(_a0 *kvs.Items, _a1 error) *MockReader_BulkGetWithContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_BulkGetWithContext_Call) RunAndReturn(run func(context.Context, string) (*kvs.Items, error)) *MockReader_BulkGetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *MockReader) Get(key string) (*kvs.Item, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *kvs.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*kvs.Item, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *kvs.Item); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockReader_Expecter) Get(key interface{}) *MockReader_Get_Call {
	return &MockReader_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockReader_Get_Call) Run(run func(key string)) *MockReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockReader_Get_Call) Return(_a0 *kvs.Item, _a1 error) *MockReader_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_Get_Call) RunAndReturn(run func(string) (*kvs.Item, error)) *MockReader_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithContext provides a mock function with given fields: ctx, key
func (_m *MockReader) GetWithContext(ctx context.Context, key string) (*kvs.Item, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetWithContext")
	}

	var r0 *kvs.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*kvs.Item, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *kvs.Item); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_GetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithContext'
type MockReader_GetWithContext_Call struct {
	*mock.Call
}

// GetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockReader_Expecter) GetWithContext(ctx interface{}, key interface{}) *MockReader_GetWithContext_Call {
	return &MockReader_GetWithContext_Call{Call: _e.mock.On("GetWithContext", ctx, key)}
}

func (_c *MockReader_GetWithContext_Call) Run(run func(ctx context.Context, key string)) *MockReader_GetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReader_GetWithContext_Call) Return(_a0 *kvs.Item, _a1 error) *MockReader_GetWithContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_GetWithContext_Call) RunAndReturn(run func(context.Context, string) (*kvs.Item, error)) *MockReader_GetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
