// Code generated by mockery. DO NOT EDIT.

package kvs

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	kvs "gitlab.com/iskaypetcom/digital/sre/tools/dev/go-kvs-client/kvs"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// BulkGet provides a mock function with given fields: keys
func (_m *MockClient) BulkGet(keys []string) (*kvs.Items, error) {
	ret := _m.Called(keys)

	if len(ret) == 0 {
		panic("no return value specified for BulkGet")
	}

	var r0 *kvs.Items
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) (*kvs.Items, error)); ok {
		return rf(keys)
	}
	if rf, ok := ret.Get(0).(func([]string) *kvs.Items); ok {
		r0 = rf(keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Items)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(keys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_BulkGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGet'
type MockClient_BulkGet_Call struct {
	*mock.Call
}

// BulkGet is a helper method to define mock.On call
//   - keys []string
func (_e *MockClient_Expecter) BulkGet(keys interface{}) *MockClient_BulkGet_Call {
	return &MockClient_BulkGet_Call{Call: _e.mock.On("BulkGet", keys)}
}

func (_c *MockClient_BulkGet_Call) Run(run func(keys []string)) *MockClient_BulkGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockClient_BulkGet_Call) Return(_a0 *kvs.Items, _a1 error) *MockClient_BulkGet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_BulkGet_Call) RunAndReturn(run func([]string) (*kvs.Items, error)) *MockClient_BulkGet_Call {
	_c.Call.Return(run)
	return _c
}

// BulkGetWithContext provides a mock function with given fields: ctx, key
func (_m *MockClient) BulkGetWithContext(ctx context.Context, key []string) (*kvs.Items, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for BulkGetWithContext")
	}

	var r0 *kvs.Items
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (*kvs.Items, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) *kvs.Items); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Items)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_BulkGetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGetWithContext'
type MockClient_BulkGetWithContext_Call struct {
	*mock.Call
}

// BulkGetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key []string
func (_e *MockClient_Expecter) BulkGetWithContext(ctx interface{}, key interface{}) *MockClient_BulkGetWithContext_Call {
	return &MockClient_BulkGetWithContext_Call{Call: _e.mock.On("BulkGetWithContext", ctx, key)}
}

func (_c *MockClient_BulkGetWithContext_Call) Run(run func(ctx context.Context, key []string)) *MockClient_BulkGetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockClient_BulkGetWithContext_Call) Return(_a0 *kvs.Items, _a1 error) *MockClient_BulkGetWithContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_BulkGetWithContext_Call) RunAndReturn(run func(context.Context, []string) (*kvs.Items, error)) *MockClient_BulkGetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// BulkSave provides a mock function with given fields: items
func (_m *MockClient) BulkSave(items *kvs.Items) error {
	ret := _m.Called(items)

	if len(ret) == 0 {
		panic("no return value specified for BulkSave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*kvs.Items) error); ok {
		r0 = rf(items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_BulkSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSave'
type MockClient_BulkSave_Call struct {
	*mock.Call
}

// BulkSave is a helper method to define mock.On call
//   - items *kvs.Items
func (_e *MockClient_Expecter) BulkSave(items interface{}) *MockClient_BulkSave_Call {
	return &MockClient_BulkSave_Call{Call: _e.mock.On("BulkSave", items)}
}

func (_c *MockClient_BulkSave_Call) Run(run func(items *kvs.Items)) *MockClient_BulkSave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*kvs.Items))
	})
	return _c
}

func (_c *MockClient_BulkSave_Call) Return(_a0 error) *MockClient_BulkSave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_BulkSave_Call) RunAndReturn(run func(*kvs.Items) error) *MockClient_BulkSave_Call {
	_c.Call.Return(run)
	return _c
}

// BulkSaveWithContext provides a mock function with given fields: ctx, items
func (_m *MockClient) BulkSaveWithContext(ctx context.Context, items *kvs.Items) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for BulkSaveWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *kvs.Items) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_BulkSaveWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSaveWithContext'
type MockClient_BulkSaveWithContext_Call struct {
	*mock.Call
}

// BulkSaveWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - items *kvs.Items
func (_e *MockClient_Expecter) BulkSaveWithContext(ctx interface{}, items interface{}) *MockClient_BulkSaveWithContext_Call {
	return &MockClient_BulkSaveWithContext_Call{Call: _e.mock.On("BulkSaveWithContext", ctx, items)}
}

func (_c *MockClient_BulkSaveWithContext_Call) Run(run func(ctx context.Context, items *kvs.Items)) *MockClient_BulkSaveWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*kvs.Items))
	})
	return _c
}

func (_c *MockClient_BulkSaveWithContext_Call) Return(_a0 error) *MockClient_BulkSaveWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_BulkSaveWithContext_Call) RunAndReturn(run func(context.Context, *kvs.Items) error) *MockClient_BulkSaveWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *MockClient) Get(key string) (*kvs.Item, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *kvs.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*kvs.Item, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *kvs.Item); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockClient_Expecter) Get(key interface{}) *MockClient_Get_Call {
	return &MockClient_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockClient_Get_Call) Run(run func(key string)) *MockClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_Get_Call) Return(_a0 *kvs.Item, _a1 error) *MockClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Get_Call) RunAndReturn(run func(string) (*kvs.Item, error)) *MockClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithContext provides a mock function with given fields: ctx, key
func (_m *MockClient) GetWithContext(ctx context.Context, key string) (*kvs.Item, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetWithContext")
	}

	var r0 *kvs.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*kvs.Item, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *kvs.Item); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithContext'
type MockClient_GetWithContext_Call struct {
	*mock.Call
}

// GetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockClient_Expecter) GetWithContext(ctx interface{}, key interface{}) *MockClient_GetWithContext_Call {
	return &MockClient_GetWithContext_Call{Call: _e.mock.On("GetWithContext", ctx, key)}
}

func (_c *MockClient_GetWithContext_Call) Run(run func(ctx context.Context, key string)) *MockClient_GetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetWithContext_Call) Return(_a0 *kvs.Item, _a1 error) *MockClient_GetWithContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetWithContext_Call) RunAndReturn(run func(context.Context, string) (*kvs.Item, error)) *MockClient_GetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: key, item
func (_m *MockClient) Save(key string, item *kvs.Item) error {
	ret := _m.Called(key, item)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *kvs.Item) error); ok {
		r0 = rf(key, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockClient_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - key string
//   - item *kvs.Item
func (_e *MockClient_Expecter) Save(key interface{}, item interface{}) *MockClient_Save_Call {
	return &MockClient_Save_Call{Call: _e.mock.On("Save", key, item)}
}

func (_c *MockClient_Save_Call) Run(run func(key string, item *kvs.Item)) *MockClient_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*kvs.Item))
	})
	return _c
}

func (_c *MockClient_Save_Call) Return(_a0 error) *MockClient_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Save_Call) RunAndReturn(run func(string, *kvs.Item) error) *MockClient_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveWithContext provides a mock function with given fields: ctx, key, item
func (_m *MockClient) SaveWithContext(ctx context.Context, key string, item *kvs.Item) error {
	ret := _m.Called(ctx, key, item)

	if len(ret) == 0 {
		panic("no return value specified for SaveWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *kvs.Item) error); ok {
		r0 = rf(ctx, key, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_SaveWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWithContext'
type MockClient_SaveWithContext_Call struct {
	*mock.Call
}

// SaveWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - item *kvs.Item
func (_e *MockClient_Expecter) SaveWithContext(ctx interface{}, key interface{}, item interface{}) *MockClient_SaveWithContext_Call {
	return &MockClient_SaveWithContext_Call{Call: _e.mock.On("SaveWithContext", ctx, key, item)}
}

func (_c *MockClient_SaveWithContext_Call) Run(run func(ctx context.Context, key string, item *kvs.Item)) *MockClient_SaveWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*kvs.Item))
	})
	return _c
}

func (_c *MockClient_SaveWithContext_Call) Return(_a0 error) *MockClient_SaveWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_SaveWithContext_Call) RunAndReturn(run func(context.Context, string, *kvs.Item) error) *MockClient_SaveWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
