// Code generated by mockery. DO NOT EDIT.

package kvs

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	kvs "gitlab.com/iskaypetcom/digital/sre/tools/dev/go-kvs-client/kvs"
)

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// BulkSave provides a mock function with given fields: items
func (_m *MockWriter) BulkSave(items *kvs.Items) error {
	ret := _m.Called(items)

	if len(ret) == 0 {
		panic("no return value specified for BulkSave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*kvs.Items) error); ok {
		r0 = rf(items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriter_BulkSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSave'
type MockWriter_BulkSave_Call struct {
	*mock.Call
}

// BulkSave is a helper method to define mock.On call
//   - items *kvs.Items
func (_e *MockWriter_Expecter) BulkSave(items interface{}) *MockWriter_BulkSave_Call {
	return &MockWriter_BulkSave_Call{Call: _e.mock.On("BulkSave", items)}
}

func (_c *MockWriter_BulkSave_Call) Run(run func(items *kvs.Items)) *MockWriter_BulkSave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*kvs.Items))
	})
	return _c
}

func (_c *MockWriter_BulkSave_Call) Return(_a0 error) *MockWriter_BulkSave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriter_BulkSave_Call) RunAndReturn(run func(*kvs.Items) error) *MockWriter_BulkSave_Call {
	_c.Call.Return(run)
	return _c
}

// BulkSaveWithContext provides a mock function with given fields: ctx, items
func (_m *MockWriter) BulkSaveWithContext(ctx context.Context, items *kvs.Items) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for BulkSaveWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *kvs.Items) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriter_BulkSaveWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSaveWithContext'
type MockWriter_BulkSaveWithContext_Call struct {
	*mock.Call
}

// BulkSaveWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - items *kvs.Items
func (_e *MockWriter_Expecter) BulkSaveWithContext(ctx interface{}, items interface{}) *MockWriter_BulkSaveWithContext_Call {
	return &MockWriter_BulkSaveWithContext_Call{Call: _e.mock.On("BulkSaveWithContext", ctx, items)}
}

func (_c *MockWriter_BulkSaveWithContext_Call) Run(run func(ctx context.Context, items *kvs.Items)) *MockWriter_BulkSaveWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*kvs.Items))
	})
	return _c
}

func (_c *MockWriter_BulkSaveWithContext_Call) Return(_a0 error) *MockWriter_BulkSaveWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriter_BulkSaveWithContext_Call) RunAndReturn(run func(context.Context, *kvs.Items) error) *MockWriter_BulkSaveWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: key, item
func (_m *MockWriter) Save(key string, item *kvs.Item) error {
	ret := _m.Called(key, item)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *kvs.Item) error); ok {
		r0 = rf(key, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriter_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockWriter_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - key string
//   - item *kvs.Item
func (_e *MockWriter_Expecter) Save(key interface{}, item interface{}) *MockWriter_Save_Call {
	return &MockWriter_Save_Call{Call: _e.mock.On("Save", key, item)}
}

func (_c *MockWriter_Save_Call) Run(run func(key string, item *kvs.Item)) *MockWriter_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*kvs.Item))
	})
	return _c
}

func (_c *MockWriter_Save_Call) Return(_a0 error) *MockWriter_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriter_Save_Call) RunAndReturn(run func(string, *kvs.Item) error) *MockWriter_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveWithContext provides a mock function with given fields: ctx, items
func (_m *MockWriter) SaveWithContext(ctx context.Context, items *kvs.Items) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for SaveWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *kvs.Items) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriter_SaveWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWithContext'
type MockWriter_SaveWithContext_Call struct {
	*mock.Call
}

// SaveWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - items *kvs.Items
func (_e *MockWriter_Expecter) SaveWithContext(ctx interface{}, items interface{}) *MockWriter_SaveWithContext_Call {
	return &MockWriter_SaveWithContext_Call{Call: _e.mock.On("SaveWithContext", ctx, items)}
}

func (_c *MockWriter_SaveWithContext_Call) Run(run func(ctx context.Context, items *kvs.Items)) *MockWriter_SaveWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*kvs.Items))
	})
	return _c
}

func (_c *MockWriter_SaveWithContext_Call) Return(_a0 error) *MockWriter_SaveWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriter_SaveWithContext_Call) RunAndReturn(run func(context.Context, *kvs.Items) error) *MockWriter_SaveWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriter {
	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
