// Code generated by mockery. DO NOT EDIT.

package kvs

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	kvs "gitlab.com/iskaypetcom/digital/sre/tools/dev/go-kvs-client/kvs"
)

// MockLowLevelClient is an autogenerated mock type for the KVSClient type
type MockLowLevelClient struct {
	mock.Mock
}

type MockLowLevelClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLowLevelClient) EXPECT() *MockLowLevelClient_Expecter {
	return &MockLowLevelClient_Expecter{mock: &_m.Mock}
}

// BulkGet provides a mock function with given fields: keys
func (_m *MockLowLevelClient) BulkGet(keys []string) (*kvs.Items, error) {
	ret := _m.Called(keys)

	if len(ret) == 0 {
		panic("no return value specified for BulkGet")
	}

	var r0 *kvs.Items
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) (*kvs.Items, error)); ok {
		return rf(keys)
	}
	if rf, ok := ret.Get(0).(func([]string) *kvs.Items); ok {
		r0 = rf(keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Items)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(keys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLowLevelClient_BulkGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGet'
type MockLowLevelClient_BulkGet_Call struct {
	*mock.Call
}

// BulkGet is a helper method to define mock.On call
//   - keys []string
func (_e *MockLowLevelClient_Expecter) BulkGet(keys interface{}) *MockLowLevelClient_BulkGet_Call {
	return &MockLowLevelClient_BulkGet_Call{Call: _e.mock.On("BulkGet", keys)}
}

func (_c *MockLowLevelClient_BulkGet_Call) Run(run func(keys []string)) *MockLowLevelClient_BulkGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockLowLevelClient_BulkGet_Call) Return(_a0 *kvs.Items, _a1 error) *MockLowLevelClient_BulkGet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLowLevelClient_BulkGet_Call) RunAndReturn(run func([]string) (*kvs.Items, error)) *MockLowLevelClient_BulkGet_Call {
	_c.Call.Return(run)
	return _c
}

// BulkGetWithContext provides a mock function with given fields: ctx, key
func (_m *MockLowLevelClient) BulkGetWithContext(ctx context.Context, key []string) (*kvs.Items, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for BulkGetWithContext")
	}

	var r0 *kvs.Items
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (*kvs.Items, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) *kvs.Items); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Items)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLowLevelClient_BulkGetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGetWithContext'
type MockLowLevelClient_BulkGetWithContext_Call struct {
	*mock.Call
}

// BulkGetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key []string
func (_e *MockLowLevelClient_Expecter) BulkGetWithContext(ctx interface{}, key interface{}) *MockLowLevelClient_BulkGetWithContext_Call {
	return &MockLowLevelClient_BulkGetWithContext_Call{Call: _e.mock.On("BulkGetWithContext", ctx, key)}
}

func (_c *MockLowLevelClient_BulkGetWithContext_Call) Run(run func(ctx context.Context, key []string)) *MockLowLevelClient_BulkGetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockLowLevelClient_BulkGetWithContext_Call) Return(_a0 *kvs.Items, _a1 error) *MockLowLevelClient_BulkGetWithContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLowLevelClient_BulkGetWithContext_Call) RunAndReturn(run func(context.Context, []string) (*kvs.Items, error)) *MockLowLevelClient_BulkGetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// BulkSave provides a mock function with given fields: items
func (_m *MockLowLevelClient) BulkSave(items *kvs.Items) error {
	ret := _m.Called(items)

	if len(ret) == 0 {
		panic("no return value specified for BulkSave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*kvs.Items) error); ok {
		r0 = rf(items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLowLevelClient_BulkSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSave'
type MockLowLevelClient_BulkSave_Call struct {
	*mock.Call
}

// BulkSave is a helper method to define mock.On call
//   - items *kvs.Items
func (_e *MockLowLevelClient_Expecter) BulkSave(items interface{}) *MockLowLevelClient_BulkSave_Call {
	return &MockLowLevelClient_BulkSave_Call{Call: _e.mock.On("BulkSave", items)}
}

func (_c *MockLowLevelClient_BulkSave_Call) Run(run func(items *kvs.Items)) *MockLowLevelClient_BulkSave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*kvs.Items))
	})
	return _c
}

func (_c *MockLowLevelClient_BulkSave_Call) Return(_a0 error) *MockLowLevelClient_BulkSave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLowLevelClient_BulkSave_Call) RunAndReturn(run func(*kvs.Items) error) *MockLowLevelClient_BulkSave_Call {
	_c.Call.Return(run)
	return _c
}

// BulkSaveWithContext provides a mock function with given fields: ctx, items
func (_m *MockLowLevelClient) BulkSaveWithContext(ctx context.Context, items *kvs.Items) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for BulkSaveWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *kvs.Items) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLowLevelClient_BulkSaveWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkSaveWithContext'
type MockLowLevelClient_BulkSaveWithContext_Call struct {
	*mock.Call
}

// BulkSaveWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - items *kvs.Items
func (_e *MockLowLevelClient_Expecter) BulkSaveWithContext(ctx interface{}, items interface{}) *MockLowLevelClient_BulkSaveWithContext_Call {
	return &MockLowLevelClient_BulkSaveWithContext_Call{Call: _e.mock.On("BulkSaveWithContext", ctx, items)}
}

func (_c *MockLowLevelClient_BulkSaveWithContext_Call) Run(run func(ctx context.Context, items *kvs.Items)) *MockLowLevelClient_BulkSaveWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*kvs.Items))
	})
	return _c
}

func (_c *MockLowLevelClient_BulkSaveWithContext_Call) Return(_a0 error) *MockLowLevelClient_BulkSaveWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLowLevelClient_BulkSaveWithContext_Call) RunAndReturn(run func(context.Context, *kvs.Items) error) *MockLowLevelClient_BulkSaveWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *MockLowLevelClient) Get(key string) (*kvs.Item, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *kvs.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*kvs.Item, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *kvs.Item); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLowLevelClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockLowLevelClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockLowLevelClient_Expecter) Get(key interface{}) *MockLowLevelClient_Get_Call {
	return &MockLowLevelClient_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockLowLevelClient_Get_Call) Run(run func(key string)) *MockLowLevelClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLowLevelClient_Get_Call) Return(_a0 *kvs.Item, _a1 error) *MockLowLevelClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLowLevelClient_Get_Call) RunAndReturn(run func(string) (*kvs.Item, error)) *MockLowLevelClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetContainerName provides a mock function with given fields:
func (_m *MockLowLevelClient) ContainerName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContainerName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockLowLevelClient_GetContainerName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerName'
type MockLowLevelClient_GetContainerName_Call struct {
	*mock.Call
}

// GetContainerName is a helper method to define mock.On call
func (_e *MockLowLevelClient_Expecter) GetContainerName() *MockLowLevelClient_GetContainerName_Call {
	return &MockLowLevelClient_GetContainerName_Call{Call: _e.mock.On("ContainerName")}
}

func (_c *MockLowLevelClient_GetContainerName_Call) Run(run func()) *MockLowLevelClient_GetContainerName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLowLevelClient_GetContainerName_Call) Return(_a0 string) *MockLowLevelClient_GetContainerName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLowLevelClient_GetContainerName_Call) RunAndReturn(run func() string) *MockLowLevelClient_GetContainerName_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithContext provides a mock function with given fields: ctx, key
func (_m *MockLowLevelClient) GetWithContext(ctx context.Context, key string) (*kvs.Item, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetWithContext")
	}

	var r0 *kvs.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*kvs.Item, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *kvs.Item); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kvs.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLowLevelClient_GetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithContext'
type MockLowLevelClient_GetWithContext_Call struct {
	*mock.Call
}

// GetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockLowLevelClient_Expecter) GetWithContext(ctx interface{}, key interface{}) *MockLowLevelClient_GetWithContext_Call {
	return &MockLowLevelClient_GetWithContext_Call{Call: _e.mock.On("GetWithContext", ctx, key)}
}

func (_c *MockLowLevelClient_GetWithContext_Call) Run(run func(ctx context.Context, key string)) *MockLowLevelClient_GetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLowLevelClient_GetWithContext_Call) Return(_a0 *kvs.Item, _a1 error) *MockLowLevelClient_GetWithContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLowLevelClient_GetWithContext_Call) RunAndReturn(run func(context.Context, string) (*kvs.Item, error)) *MockLowLevelClient_GetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: key, item
func (_m *MockLowLevelClient) Save(key string, item *kvs.Item) error {
	ret := _m.Called(key, item)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *kvs.Item) error); ok {
		r0 = rf(key, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLowLevelClient_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockLowLevelClient_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - key string
//   - item *kvs.Item
func (_e *MockLowLevelClient_Expecter) Save(key interface{}, item interface{}) *MockLowLevelClient_Save_Call {
	return &MockLowLevelClient_Save_Call{Call: _e.mock.On("Save", key, item)}
}

func (_c *MockLowLevelClient_Save_Call) Run(run func(key string, item *kvs.Item)) *MockLowLevelClient_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*kvs.Item))
	})
	return _c
}

func (_c *MockLowLevelClient_Save_Call) Return(_a0 error) *MockLowLevelClient_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLowLevelClient_Save_Call) RunAndReturn(run func(string, *kvs.Item) error) *MockLowLevelClient_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveWithContext provides a mock function with given fields: ctx, key, item
func (_m *MockLowLevelClient) SaveWithContext(ctx context.Context, key string, item *kvs.Item) error {
	ret := _m.Called(ctx, key, item)

	if len(ret) == 0 {
		panic("no return value specified for SaveWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *kvs.Item) error); ok {
		r0 = rf(ctx, key, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLowLevelClient_SaveWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWithContext'
type MockLowLevelClient_SaveWithContext_Call struct {
	*mock.Call
}

// SaveWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - item *kvs.Item
func (_e *MockLowLevelClient_Expecter) SaveWithContext(ctx interface{}, key interface{}, item interface{}) *MockLowLevelClient_SaveWithContext_Call {
	return &MockLowLevelClient_SaveWithContext_Call{Call: _e.mock.On("SaveWithContext", ctx, key, item)}
}

func (_c *MockLowLevelClient_SaveWithContext_Call) Run(run func(ctx context.Context, key string, item *kvs.Item)) *MockLowLevelClient_SaveWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*kvs.Item))
	})
	return _c
}

func (_c *MockLowLevelClient_SaveWithContext_Call) Return(_a0 error) *MockLowLevelClient_SaveWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLowLevelClient_SaveWithContext_Call) RunAndReturn(run func(context.Context, string, *kvs.Item) error) *MockLowLevelClient_SaveWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLowLevelClient creates a new instance of MockLowLevelClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLowLevelClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLowLevelClient {
	mock := &MockLowLevelClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
