// Code generated by mockery. DO NOT EDIT.

package dynamodb

import (
	mock "github.com/stretchr/testify/mock"
	dynamodb "gitlab.com/iskaypetcom/digital/sre/tools/dev/go-kvs-client/kvs/dynamodb"
)

// MockBuilderOptions is an autogenerated mock type for the BuilderOptions type
type MockBuilderOptions struct {
	mock.Mock
}

type MockBuilderOptions_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBuilderOptions) EXPECT() *MockBuilderOptions_Expecter {
	return &MockBuilderOptions_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: f
func (_m *MockBuilderOptions) Execute(f *dynamodb.Builder) {
	_m.Called(f)
}

// MockBuilderOptions_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockBuilderOptions_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - f *dynamodb.Builder
func (_e *MockBuilderOptions_Expecter) Execute(f interface{}) *MockBuilderOptions_Execute_Call {
	return &MockBuilderOptions_Execute_Call{Call: _e.mock.On("Execute", f)}
}

func (_c *MockBuilderOptions_Execute_Call) Run(run func(f *dynamodb.Builder)) *MockBuilderOptions_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dynamodb.Builder))
	})
	return _c
}

func (_c *MockBuilderOptions_Execute_Call) Return() *MockBuilderOptions_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuilderOptions_Execute_Call) RunAndReturn(run func(*dynamodb.Builder)) *MockBuilderOptions_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBuilderOptions creates a new instance of MockBuilderOptions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBuilderOptions(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBuilderOptions {
	mock := &MockBuilderOptions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
