{
 "title": "KVS - Key Value Store",
 "tags": [ "apm" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(__kvs_connection,k8s_cluster_name)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(__kvs_connection{k8s_cluster_name=\"$environment\"},container)"
    }
   },
   {
    "name": "client_name",
    "label": "Client name",
    "query": {
     "query": "label_values(__kvs_connection{k8s_cluster_name=\"$environment\", container=\"$application\"},client_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "READ Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "__kvs_connection{k8s_cluster_name=\"$environment\", container=\"$application\", client_name=\"$client_name\", type=\"get\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WRITE Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "__kvs_connection{k8s_cluster_name=\"$environment\", container=\"$application\", client_name=\"$client_name\", type=\"save\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(__kvs_stats{k8s_cluster_name=\"$environment\", container=\"$application\", client_name=\"$client_name\", stats=\"hit\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Miss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(__kvs_stats{k8s_cluster_name=\"$environment\", container=\"$application\", client_name=\"$client_name\", stats=\"miss\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  sum(__kvs_stats{k8s_cluster_name=\"$environment\", container=\"$application\", client_name=\"$client_name\", stats=\"hit\"})\n) / (\n  sum(__kvs_stats{k8s_cluster_name=\"$environment\", container=\"$application\", client_name=\"$client_name\", stats=\"hit\"})\n  +\n  sum(__kvs_stats{k8s_cluster_name=\"$environment\", container=\"$application\", client_name=\"$client_name\", stats=\"miss\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  sum(__kvs_stats{k8s_cluster_name=\"$environment\", container=\"$application\", client_name=\"$client_name\", stats=\"hit\"})\n) / (\n  sum(__kvs_stats{k8s_cluster_name=\"$environment\", container=\"$application\", client_name=\"$client_name\", stats=\"hit\"})\n  +\n  sum(__kvs_stats{k8s_cluster_name=\"$environment\", container=\"$application\", client_name=\"$client_name\", stats=\"miss\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}